
GET http://localhost:3000/book

###

POST http://localhost:3000/book
Content-Type: application/json

{
    "bookId": "1",
    "bookName": "shakei",
    "bookPages": "52",
    "bookAuthor": "shakei2"
}

###

PUT http://localhost:3000/book

###

DELETE  htpp://localhost:3000/book